# Generated by Django 4.2 on 2024-09-26 11:04

import core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='businesses/')),
                ('footer_image', models.ImageField(blank=True, null=True, upload_to='businesses/')),
                ('description', models.TextField(blank=True, max_length=20000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qr_code', models.CharField(default=core.utils.generate_small_uuid, editable=False, max_length=100, unique=True)),
                ('qr_img', models.ImageField(blank=True, null=True, upload_to='qrs/')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrs', to='models.business')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessQRCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(allow_unicode=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('chat_id', models.CharField(max_length=120)),
                ('last_members_count', models.PositiveIntegerField(default=0)),
                ('last_members_check', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsappGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('chat_id', models.CharField(max_length=120)),
                ('last_members_count', models.PositiveIntegerField(default=0)),
                ('last_members_check', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SysUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='models.business')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='me', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeadsClicks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads_clicks', to='models.business')),
                ('qr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads_clicks', to='models.businessqr')),
            ],
        ),
        migrations.CreateModel(
            name='ContentSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='contents/')),
                ('send_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approve_state', models.CharField(choices=[('A', 'Approved'), ('P', 'Pending'), ('R', 'Rejected')], default='P', max_length=1)),
                ('approve_date', models.DateTimeField(blank=True, null=True)),
                ('is_whatsapp_sent', models.BooleanField(default=False)),
                ('is_telegram_sent', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contentSchedules', to='models.business')),
                ('categories', models.ManyToManyField(blank=True, related_name='contentSchedules', to='models.category')),
            ],
            options={
                'ordering': ['-send_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='all_telegram_urls',
            field=models.ManyToManyField(related_name='all_telegram_categories', to='models.telegramgroup'),
        ),
        migrations.AddField(
            model_name='category',
            name='all_whatsapp_urls',
            field=models.ManyToManyField(related_name='all_whatsapp_categories', to='models.whatsappgroup'),
        ),
        migrations.AddField(
            model_name='category',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='models.business'),
        ),
        migrations.AddField(
            model_name='category',
            name='open_telegram_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='open_telegram_categories', to='models.telegramgroup'),
        ),
        migrations.AddField(
            model_name='category',
            name='open_whatsapp_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='open_whatsapp_categories', to='models.whatsappgroup'),
        ),
        migrations.CreateModel(
            name='CategoriesClicks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group_type', models.CharField(choices=[('whatsapp', 'whatsapp'), ('telegram', 'telegram')], default='whatsapp', max_length=100)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_clicks', to='models.business')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_clicks', to='models.category')),
                ('qr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories_clicks', to='models.businessqr')),
            ],
        ),
        migrations.AddField(
            model_name='businessqr',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrs', to='models.businessqrcategories'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('slug', 'business')},
        ),
        migrations.AlterUniqueTogether(
            name='businessqr',
            unique_together={('name', 'business', 'category')},
        ),
    ]
