# Generated by Django 5.0.2 on 2024-02-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_category_open_telegram_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contentschedule',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='contentSchedules', to='models.category'),
        ),
        migrations.AlterField(
            model_name='contentschedule',
            name='message',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contentschedule',
            name='send_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'business')},
        ),
    ]
