# Generated by Django 4.2 on 2024-10-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_bizmessages_messagelink_messagelinkclick_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bizmessages',
            options={'verbose_name': 'business message', 'verbose_name_plural': 'business messages'},
        ),
        migrations.RemoveField(
            model_name='bizmessages',
            name='telegram_groups',
        ),
        migrations.RemoveField(
            model_name='bizmessages',
            name='whatsapp_groups',
        ),
        migrations.AddField(
            model_name='messagelink',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='תיאור'),
        ),
        migrations.AlterField(
            model_name='bizmessages',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='messages', to='models.category', verbose_name='קטגוריות'),
        ),
    ]
