# Generated by Django 4.2 on 2024-10-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_alter_bizmessages_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='display name'),
        ),
        migrations.AddField(
            model_name='business',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='businesses/', verbose_name='favicon'),
        ),
    ]
