# Generated by Django 4.2 on 2024-10-06 00:26

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_remove_bizmessages_categories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bizmessages',
            old_name='message',
            new_name='messageTxt',
        ),
        migrations.AddField(
            model_name='bizmessages',
            name='uid',
            field=models.CharField(default=core.utils.generate_small_uuid, editable=False, max_length=100, unique=True, verbose_name='uid'),
        ),
    ]
