# Generated by Django 5.1.1 on 2024-10-06 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_rename_message_bizmessages_messagetxt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagelink',
            name='link',
        ),
        migrations.AddField(
            model_name='messagelink',
            name='url',
            field=models.URLField(default='https://google.com', max_length=2000, verbose_name='url'),
            preserve_default=False,
        ),
    ]
