# Generated by Django 5.0.2 on 2024-03-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_telegramgroup_whatsappgroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramgroup',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='whatsappgroup',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
