# Generated by Django 4.2 on 2024-10-06 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_remove_messagelink_link_messagelink_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagecategory',
            name='send_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='send at'),
        ),
    ]
