# Generated by Django 4.2 on 2024-10-06 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_alter_messagecategory_send_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagecategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='models.category', verbose_name='קטגוריה'),
        ),
    ]
