# Generated by Django 5.0.2 on 2024-03-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_telegramgroup_name_whatsappgroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramgroup',
            name='last_members_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappgroup',
            name='last_members_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
