# Generated by Django 4.2 on 2024-10-07 20:03

import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_alter_messagecategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecategory',
            name='uid',
            field=models.CharField(default=core.utils.generate_small_uuid, editable=False, max_length=100, unique=True, verbose_name='uid'),
        ),
        migrations.AlterField(
            model_name='bizmessages',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='models.business', verbose_name='עסק'),
        ),
    ]
