# Generated by Django 5.0.2 on 2024-03-05 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_alter_telegramgroup_last_members_check_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentschedule',
            name='approve_telegram_id',
        ),
    ]
