# Generated by Django 4.2 on 2024-10-07 21:53

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0012_messagecategory_uid_alter_bizmessages_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='uid',
            field=models.CharField(default=core.utils.generate_small_uuid, editable=False, max_length=100, verbose_name='uid'),
        ),
    ]
