# Generated by Django 4.2 on 2024-03-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0012_remove_contentschedule_approve_telegram_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentschedule',
            old_name='is_sent',
            new_name='is_telegram_sent',
        ),
        migrations.AddField(
            model_name='contentschedule',
            name='is_whatsapp_sent',
            field=models.BooleanField(default=False),
        ),
    ]
