# Generated by Django 4.2 on 2024-09-25 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0014_alter_contentschedule_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessQRCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='qrs/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrs', to='models.businessqrcategories')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='qrs',
            field=models.ManyToManyField(related_name='businesses', to='models.businessqr'),
        ),
    ]
