# Generated by Django 4.2 on 2024-10-07 21:59

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0014_alter_category_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagelinktracker',
            name='link',
        ),
        migrations.RemoveField(
            model_name='messagelinktracker',
            name='telegram_group',
        ),
        migrations.RemoveField(
            model_name='messagelinktracker',
            name='whatsapp_group',
        ),
        migrations.AddField(
            model_name='messagelink',
            name='uid',
            field=models.CharField(default=core.utils.generate_small_uuid, editable=False, max_length=100, verbose_name='uid'),
        ),
        migrations.DeleteModel(
            name='MessageLinkClick',
        ),
        migrations.DeleteModel(
            name='MessageLinkTracker',
        ),
    ]
