# Generated by Django 4.2 on 2024-10-07 22:00

import core.utils
from django.db import migrations, models
def generate_uuid_for_existing_messagelinks(apps, schema_editor):
    MessageLink = apps.get_model('models', 'MessageLink')
    for messagelink in MessageLink.objects.all():
        messagelink.uid = core.utils.generate_small_uuid()
        messagelink.save()

class Migration(migrations.Migration):

    dependencies = [
        ('models', '0015_remove_messagelinktracker_link_and_more'),
    ]

    operations = [
        migrations.RunPython(generate_uuid_for_existing_messagelinks),
        migrations.AlterField(
            model_name='messagelink',
            name='uid',
            field=models.CharField(default=core.utils.generate_small_uuid, editable=False, max_length=100, unique=True, verbose_name='uid'),
        ),
    ]
