# Generated by Django 4.2 on 2024-09-25 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0015_businessqrcategories_businessqr_business_qrs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='qrs',
        ),
        migrations.AddField(
            model_name='businessqr',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='qrs', to='models.business'),
            preserve_default=False,
        ),
    ]
