# Generated by Django 4.2 on 2024-09-25 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0017_remove_businessqr_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadsClicks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creeated_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads_clicks', to='models.business')),
                ('qr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads_clicks', to='models.businessqr')),
            ],
        ),
        migrations.CreateModel(
            name='CategoriesClicks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creeated_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_clicks', to='models.business')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_clicks', to='models.category')),
                ('qr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_clicks', to='models.businessqr')),
            ],
        ),
    ]
