# Generated by Django 4.2 on 2024-10-07 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0017_messagelinkclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelinkclick',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='models.category', verbose_name='קטגוריה'),
            preserve_default=False,
        ),
    ]
