# Generated by Django 4.2 on 2024-09-25 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0018_leadsclicks_categoriesclicks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriesclicks',
            name='qr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories_clicks', to='models.businessqr'),
        ),
        migrations.AlterField(
            model_name='leadsclicks',
            name='qr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads_clicks', to='models.businessqr'),
        ),
    ]
