# Generated by Django 4.2 on 2024-09-25 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0019_alter_categoriesclicks_qr_alter_leadsclicks_qr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriesclicks',
            old_name='creeated_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='leadsclicks',
            old_name='creeated_at',
            new_name='created_at',
        ),
    ]
