# Generated by Django 4.2 on 2024-10-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0019_alter_messagelinkclick_user_agent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['business', 'the_order'], 'verbose_name': 'קטגוריה', 'verbose_name_plural': 'קטגוריות'},
        ),
        migrations.AddField(
            model_name='category',
            name='the_order',
            field=models.PositiveIntegerField(default=0, verbose_name='order'),
        ),
    ]
