# Generated by Django 4.2 on 2024-09-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0020_rename_creeated_at_categoriesclicks_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessqr',
            name='qr_img',
            field=models.ImageField(blank=True, null=True, upload_to='qrs/'),
        ),
    ]
