# Generated by Django 4.2 on 2024-09-25 12:22

from django.db import migrations, models
import uuid

def generate_small_uuid():
    return str(uuid.uuid4())[:6]



class Migration(migrations.Migration):

    dependencies = [
        ('models', '0021_businessqr_qr_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessqr',
            name='qr_code',
            field=models.CharField(default=generate_small_uuid, editable=False, max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='businessqr',
            unique_together={('name', 'business', 'category')},
        ),
    ]
