# Generated by Django 4.2 on 2024-09-25 12:24

from django.db import migrations, models
import uuid

def generate_small_uuid():
    return str(uuid.uuid4())[:6]

class Migration(migrations.Migration):

    dependencies = [
        ('models', '0022_businessqr_qr_code_alter_businessqr_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessqr',
            name='qr_code',
            field=models.CharField(default=generate_small_uuid, editable=False, max_length=100, unique=True),
        ),
    ]
