# Generated by Django 4.2 on 2024-10-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0022_auto_20241030_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessqr',
            options={'ordering': ['the_order'], 'verbose_name': 'QR של עסק', 'verbose_name_plural': 'QR של עסקים'},
        ),
        migrations.AddField(
            model_name='businessqr',
            name='the_order',
            field=models.PositiveIntegerField(default=0, verbose_name='order'),
        ),
    ]
