# Generated by Django 4.2 on 2024-09-26 06:12

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0023_alter_businessqr_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriesclicks',
            name='group_type',
            field=models.CharField(choices=[('whatsapp', 'whatsapp'), ('telegram', 'telegram')], default='whatsapp', max_length=100),
        ),
        migrations.AlterField(
            model_name='businessqr',
            name='qr_code',
            field=models.CharField(default=core.utils.generate_small_uuid, editable=False, max_length=100, unique=True),
        ),
    ]
