# Generated by Django 4.2 on 2024-09-26 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0024_categoriesclicks_group_type_alter_businessqr_qr_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('slug', 'business')},
        ),
    ]
