# Generated by Django 5.1.1 on 2024-11-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0025_remove_telegramgroup_last_members_check_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecategory',
            name='platform',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], default='telegram', max_length=20),
        ),
    ]
