# Generated by Django 4.2 on 2024-11-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0025_remove_telegramgroup_last_members_check_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_main_category',
            field=models.BooleanField(default=False, verbose_name='is main category'),
        ),
    ]
