# Generated by Django 4.2 on 2024-09-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0026_business_footer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='description',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
    ]
