# Generated by Django 4.2 on 2024-11-03 23:06

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0027_alter_messagecategory_send_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bizmessages',
            name='uid',
            field=models.CharField(default=core.utils.generate_unique_uid, editable=False, max_length=100, unique=True, verbose_name='uid'),
        ),
        migrations.AlterField(
            model_name='category',
            name='uid',
            field=models.CharField(default=core.utils.generate_unique_uid, editable=False, max_length=100, unique=True, verbose_name='uid'),
        ),
        migrations.AlterField(
            model_name='messagecategory',
            name='uid',
            field=models.CharField(default=core.utils.generate_unique_uid, editable=False, max_length=100, unique=True, verbose_name='uid'),
        ),
        migrations.AlterField(
            model_name='messagelink',
            name='uid',
            field=models.CharField(default=core.utils.generate_unique_uid, editable=False, max_length=100, unique=True, verbose_name='uid'),
        ),
    ]
