# Generated by Django 4.2 on 2024-11-03 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0029_call_business_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='telegram_fotter',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='telegram footer'),
        ),
    ]
