# Generated by Django 4.2 on 2024-11-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0030_business_telegram_fotter'),
    ]

    operations = [
        migrations.AddField(
            model_name='bizmessages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='messages/', verbose_name='image'),
        ),
    ]
