# Generated by Django 4.2 on 2024-11-05 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0031_bizmessages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ai_message_example',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='AI message example'),
        ),
        migrations.AddField(
            model_name='category',
            name='ai_message_tone',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='AI message tone'),
        ),
    ]
