# Generated by Django 5.1.1 on 2024-11-05 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0032_category_ai_message_example_category_ai_message_tone'),
    ]

    operations = [
        migrations.AddField(
            model_name='bizmessages',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='coupon code'),
        ),
        migrations.AddField(
            model_name='bizmessages',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='תיאור'),
        ),
        migrations.AddField(
            model_name='bizmessages',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='bizmessages',
            name='product_metadata',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='product metadata'),
        ),
        migrations.AddField(
            model_name='bizmessages',
            name='product_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='product name'),
        ),
    ]
