# Generated by Django 5.1.1 on 2024-11-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0033_bizmessages_coupon_code_bizmessages_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bizmessages',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='price'),
        ),
    ]
