# Generated by Django 5.1.1 on 2024-11-05 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0034_alter_bizmessages_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bizmessages',
            old_name='description',
            new_name='product_description',
        ),
    ]
