# Generated by Django 5.1.1 on 2024-11-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0035_rename_description_bizmessages_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bizmessages',
            name='coupon_code',
            field=models.CharField(default='', max_length=100, verbose_name='coupon code'),
        ),
        migrations.AlterField(
            model_name='bizmessages',
            name='price',
            field=models.CharField(default='', max_length=100, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='bizmessages',
            name='product_description',
            field=models.CharField(default='', max_length=1000, verbose_name='תיאור'),
        ),
        migrations.AlterField(
            model_name='bizmessages',
            name='product_metadata',
            field=models.CharField(default='', max_length=1000, verbose_name='product metadata'),
        ),
        migrations.AlterField(
            model_name='bizmessages',
            name='product_name',
            field=models.CharField(default='', max_length=500, verbose_name='product name'),
        ),
    ]
