# Generated by Django 4.2 on 2024-11-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0036_alter_bizmessages_coupon_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='ai_message_example',
        ),
        migrations.RemoveField(
            model_name='category',
            name='ai_message_tone',
        ),
        migrations.AddField(
            model_name='business',
            name='ai_message_correction',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='AI message correction'),
        ),
        migrations.AddField(
            model_name='business',
            name='ai_message_prompt',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='AI message prompt'),
        ),
    ]
