# Generated by Django 5.1.1 on 2024-11-16 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0026_messagecategory_platform'),
        ('models', '0040_categoriesclicks_referrer_leadsclicks_referrer_and_more'),
    ]

    operations = [
    ]
