# Generated by Django 5.1.1 on 2024-11-16 17:48

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0041_merge_20241116_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bizmessages',
            name='coupon_code',
        ),
        migrations.RemoveField(
            model_name='bizmessages',
            name='image',
        ),
        migrations.RemoveField(
            model_name='bizmessages',
            name='price',
        ),
        migrations.RemoveField(
            model_name='bizmessages',
            name='product_description',
        ),
        migrations.RemoveField(
            model_name='bizmessages',
            name='product_metadata',
        ),
        migrations.RemoveField(
            model_name='bizmessages',
            name='product_name',
        ),
        migrations.AddField(
            model_name='messagecategory',
            name='reminder_sent',
            field=models.BooleanField(default=False, verbose_name='reminder sent'),
        ),
        migrations.AlterField(
            model_name='bizmessages',
            name='uid',
            field=models.CharField(default=core.utils.generate_small_uuid, editable=False, max_length=100, unique=True, verbose_name='uid'),
        ),
    ]
