# Generated by Django 4.2 on 2024-11-24 12:28

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0042_remove_bizmessages_coupon_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bizmessages',
            name='coupon_code',
            field=models.CharField(default='', max_length=100, verbose_name='coupon code'),
        ),
        migrations.AddField(
            model_name='bizmessages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='messages/', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='bizmessages',
            name='price',
            field=models.CharField(default='', max_length=100, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='bizmessages',
            name='product_description',
            field=models.CharField(default='', max_length=1000, verbose_name='תיאור'),
        ),
        migrations.AddField(
            model_name='bizmessages',
            name='product_metadata',
            field=models.CharField(default='', max_length=1000, verbose_name='product metadata'),
        ),
        migrations.AddField(
            model_name='bizmessages',
            name='product_name',
            field=models.CharField(default='', max_length=500, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='bizmessages',
            name='uid',
            field=models.CharField(default=core.utils.generate_unique_uid, editable=False, max_length=100, unique=True, verbose_name='uid'),
        ),
    ]
