# Generated by Django 5.1.1 on 2024-12-14 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0043_bizmessages_coupon_code_bizmessages_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramgroup',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_groups', to='models.business'),
        ),
    ]
