# Generated by Django 5.1.1 on 2024-12-14 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0044_telegramgroup_business'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramgroup',
            options={},
        ),
        migrations.RemoveField(
            model_name='telegramgroup',
            name='business',
        ),
    ]
