# Generated by Django 4.2 on 2024-09-26 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('models', '0024_categoriesclicks_group_type_alter_businessqr_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaylyGroupSizeCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.business')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsappGroupSizeCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.whatsappgroup')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counting.daylygroupsizecount')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyMessagesResponsesCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('count', models.IntegerField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.business')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramGroupSizeCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.telegramgroup')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counting.daylygroupsizecount')),
            ],
        ),
    ]
