# Generated by Django 4.2 on 2024-09-26 11:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaylyGroupSizeCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.business')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsappGroupSizeCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.whatsappgroup')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counting.daylygroupsizecount')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramGroupSizeCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.telegramgroup')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counting.daylygroupsizecount')),
            ],
        ),
        migrations.CreateModel(
            name='MessagesResponsesCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('count', models.IntegerField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.business')),
            ],
        ),
        migrations.CreateModel(
            name='CallsResponsesCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('count', models.IntegerField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.business')),
            ],
        ),
    ]
