# Generated by Django 4.2 on 2024-09-26 07:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('counting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklymessagesresponsescount',
            name='created_at',
        ),
        migrations.AddField(
            model_name='weeklymessagesresponsescount',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
