# Generated by Django 4.2 on 2024-10-13 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counting', '0002_alter_callsresponsescount_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daylygroupsizecount',
            options={'ordering': ['-date'], 'verbose_name': 'Dayly Group Size Count', 'verbose_name_plural': 'Dayly Group Size Counts'},
        ),
    ]
