# Generated by Django 4.2 on 2024-09-26 10:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0027_alter_business_description'),
        ('counting', '0003_alter_weeklymessagesresponsescount_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeeklyMessagesResponsesCount',
            new_name='MessagesResponsesCount',
        ),
        migrations.RemoveField(
            model_name='daylygroupsizecount',
            name='created_at',
        ),
        migrations.AddField(
            model_name='daylygroupsizecount',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='CallsResponsesCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('count', models.IntegerField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.business')),
            ],
        ),
    ]
