# Generated by Django 5.1.1 on 2024-11-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counting', '0003_alter_daylygroupsizecount_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='daylygroupsizecount',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
