# Generated by Django 4.2 on 2024-11-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counting', '0004_callsresponsescount_rel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappgroupsizecount',
            name='count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Count'),
        ),
    ]
