# Generated by Django 5.1.1 on 2024-11-16 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counting', '0004_daylygroupsizecount_notification_sent'),
        ('counting', '0008_alter_messagesresponsescount_options'),
    ]

    operations = [
    ]
