# Generated by Django 4.2 on 2024-10-05 21:53

from django.db import migrations

# your_app_name/migrations/XXXX_create_superuser_if_debug.py
from django.conf import settings
from django.db import migrations


def create_superuser_if_debug(apps, schema_editor):
    # Import User model from the auth app
    User = apps.get_model('auth', 'User')

    # Check if DEBUG is True and if a superuser already exists
    if settings.DEBUG and not User.objects.filter(is_superuser=True).exists():
        User.objects.create_superuser(
            username='admin',
            email='admin@example.com',
            password='adminpass'
        )
        
    #   DJANGO_SUPERUSER_USERNAME: admin
    #   DJANGO_SUPERUSER_PASSWORD: adminpass
    #   DJANGO_SUPERUSER_EMAIL: admin@example.com


class Migration(migrations.Migration):

    dependencies = [
        # Make sure to replace this with the correct dependency from your app
    ]

    operations = [
        migrations.RunPython(create_superuser_if_debug),
    ]
